-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 12:02:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `godb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `godb` ;

-- -----------------------------------------------------
-- Table `godb`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`ingredients` (
  `idingredients` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `calorie` INT NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT '"NULL"',
  `quantity` INT NULL DEFAULT 1,
  PRIMARY KEY (`idingredients`),
  UNIQUE INDEX `idingredients_UNIQUE` (`idingredients` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `godb`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`list` (
  `idlist` INT NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(300) NULL DEFAULT 'Null',
  PRIMARY KEY (`idlist`),
  UNIQUE INDEX `idlist_UNIQUE` (`idlist` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 774
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `godb`.`recepie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`recepie` (
  `idrecepie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `time` TIME NULL DEFAULT NULL,
  `howto` VARCHAR(2500) NULL DEFAULT 'Cuire',
  PRIMARY KEY (`idrecepie`),
  UNIQUE INDEX `idrecepie_UNIQUE` (`idrecepie` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 575
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `godb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `godb`.`recepie_has_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`recepie_has_ingredients` (
  `recepie_idrecepie` INT NOT NULL,
  `ingredients_idingredients` INT NOT NULL,
  `needed_quantity` INT NOT NULL,
  PRIMARY KEY (`recepie_idrecepie`, `ingredients_idingredients`),
  INDEX `fk_recepie_has_ingredients_ingredients1_idx` (`ingredients_idingredients` ASC) VISIBLE,
  INDEX `fk_recepie_has_ingredients_recepie1_idx` (`recepie_idrecepie` ASC) VISIBLE,
  CONSTRAINT `fk_recepie_has_ingredients_recepie1`
    FOREIGN KEY (`recepie_idrecepie`)
    REFERENCES `godb`.`recepie` (`idrecepie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recepie_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_idingredients`)
    REFERENCES `godb`.`ingredients` (`idingredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
